### ISSUE TITLE
Saving code add characters or spaces

### ISSUE THREAD

**Issue by ezkoombea** [panoply/vscode-liquid#101]
Until today everything was working perfectly. But now every single time I save a liquid file, it adds characters, letters or tab spacing into the file, modifying the code indentation. I had disabled/enabled and uninstalled/installed the extension multiple times but without success to fix the bug. When is disabled, the issue is gone, but this extension helps a lot while coding.

**Comment by panoply** [comment]
Hey @ezkoombea 

So the update was going to be a bit of transition for users. A lot has changed. You can always use the previous version as per [documentation](https://github.com/panoply/vscode-liquid#continue-using-v230). Can you share with me this issues you are having and share the code sample? 

Let's try get to the bottom of it.

**Comment by panoply** [comment]
This might be due to a defect on multiline tags, try enabling `forceIndent` and see how you go.

**Comment by panoply** [comment]
@ezkoombea I need more information here but I am going to assume this is occurring in newlined tags similar to https://github.com/panoply/prettify/issues/34. For example:

```liquid
<div>
  {% render 'snippet' 
     param2: 'foo',
     param2: 'bar'
  %}
</div>
```

In any sense, [**v3.1.0** ](https://github.com/panoply/vscode-liquid/pull/110) will likely solve this issue. If I am incorrect here, please let me know. 

Thanks

**Comment by panoply** [comment]
Closing this. Any defects pertaining to this should now be resolved, if anything persists then open a new issue.
