### ISSUE TITLE
Comments only being added with opening tags

### ISSUE THREAD

**Issue by davidwarrington** [panoply/vscode-liquid#102]
First off - congratulations on getting this over the line!

Onto the issue:

Using the shortcut `cmd + /` to create a liquid comment, only the opening tag is added to the beginning of each the area.

https://user-images.githubusercontent.com/9138568/192863429-c833c119-5292-4cd1-bb26-31c055f40138.mov

It's happening in every file I try, but in case it helps, here's the code I'm testing in the video

```liquid
<div class="prg-ProgressBar {%- if value >= max %} prg-ProgressBar-complete{%- endif -%}" style="--ProgressBar_Max: {{ max }}; --ProgressBar_Value: {{ value }};">
  <p class="prg-ProgressBar_Label fz-14_171">
    {%- if value >= max -%}
      <span class="prg-ProgressBar_Icon">
        {%- render 'icon-check' -%}
      </span>
    {%- endif -%}

    {{ label }}
  </p>

  <div class="prg-ProgressBar_Bar"></div>
</div>
```

**Comment by panoply** [comment]
Thanks for all the help and discussions to get it/us here!

I've actually never used this command. I will need to have a look and see what might be causing it. I am about to publish a patch, tell me it works. I was using a matching prefix in snippets, but I am not sure if they are related to this?

**Comment by panoply** [comment]
@davidwarrington can you see if the patch release #103 fixes this?

**Comment by davidwarrington** [comment]
That update doesn't seem to do it.

I've had a quick scan of the project files and stumbled across this in `liquid.language-configuration.json` which I think is the cause:

```jsonc
{
	"comments": {
		"lineComment": "{% #",
		"blockComment": [
			"{%- comment -%}",
			"{%- endcomment -%}",
			"{% comment %}",
			"{% endcomment %}"
		]
	},
	// ...
}
```

I know very little about VSCode extensions so I'm hoping I'm wrong, or that there is a workaround, but from a very quick scan it looks like `lineComment` doesn't support > 1 entry, I'm guessing because technically the line comment you're using here is still a block comment as it doesn't force the entire line to become a comment.

I've tried modifier my install of this extension and removing `lineComment` and reducing the `blockComment` option to two items such as below seems to work, however it I'm not sure why removing `lineComment` is necessary where when a multiline block is highlighted. Also doing something like below would be enforcing either a whitespace-controlled or no-whitespace-controlled opinion.

```jsonc
{
	"comments": {
		"blockComment": [
			"{%- comment -%}",
			"{%- endcomment -%}",
		]
	},
}
```

Also just on a personal level I'd really love to default to the inline comments but it's more hassle than it's usually worth if my editor isn't automating writing it for me for multiline comments.

Having a quick Google I also see there's this issue microsoft/vscode#64659 I can see there is some demand for more flexibility here, but no responses.

**Comment by panoply** [comment]
That's the one. I'll PR

**Comment by panoply** [comment]
🚢 [v3.0.2](#104)
