### ISSUE TITLE
Readme Link to Release Notes Broken

### ISSUE THREAD

**Issue by JMayfield** [panoply/vscode-liquid#107]
The link to the release notes for v3.0 seems to be 404ing in the [Updating to 3.0.0](https://github.com/panoply/vscode-liquid#updating-to-v300) section of the readme.

I was looking for some information about the deprecated `.liquidrc` functionality.

By the way, I love your extension @panoply, and have benefited from its use for years now. Looking forward to getting all of the kinks ironed out of the v3 upgrade. Thanks for continuing this work!

**Comment by panoply** [comment]
Hey @JMayfield  Thanks so much for taking the time here. I just fixed this.

> I was looking for some information about the deprecated .liquidrc functionality.

So a fair bit changed on this front. The old configuration is deprecated. I tried my best to inform upon the changes in [Release Notes](https://github.com/panoply/vscode-liquid/releases/tag/v3.0.0). The `.liquidrc` is a lot easier to navigate now and has intellisense so things are much clearer overall. You can also use a `prettify` field in a `package.json` file if your project is using node. 

>  Looking forward to getting all of the kinks ironed out of the v3 upgrade.

Indeed! It was a long time between updates and I really deliberated between bumping but in the end I needed the collaboration from users to help with the ironing, hoping to get everything solved in next minor v3.1.0.
