### ISSUE TITLE
Shopify liquid json issue

### ISSUE THREAD

**Issue by onderakbulut** [panoply/vscode-liquid#112]
![Screenshot_1](https://user-images.githubusercontent.com/64356670/193401401-3c6911e8-8e6f-43e5-af7f-fe8e37380fde.png)

Stated as in the screenshot. when I was save the file json text is becoming complicated 
I look forward to your ideas and suggestions. Thank you so much!

**Comment by panoply** [comment]
Hey @onderakbulut,

Do you have any other extensions active for Liquid? It seems like highlighting support is also not being applied.

**Comment by onderakbulut** [comment]
Hi @panoply 
Shopify liquid template snippets and other plugins
![Screenshot_1](https://user-images.githubusercontent.com/64356670/193406989-8093d3b7-35d1-45df-98ae-1a53446d0b50.png)
![Screenshot_2](https://user-images.githubusercontent.com/64356670/193406991-9a7fa1ab-e272-48f5-adf6-2c943cda88fa.png)

**Comment by panoply** [comment]
oke, can you share your workspace settings? Have you gone over the documentation?

**Comment by onderakbulut** [comment]
sorry for the delay this is settings.json file

`{
    "liveSassCompile.settings.formats": [
        {
            "format": "expanded",
            "extensionName": ".css",
            "savePath": "/assets/css"
        }
    ],
    "liveSassCompile.settings.excludeList": [
        "'/**/node_modules/**'",
        "'/plugins/**'"
    ],
    "liveSassCompile.settings.generateMap": false,
    "workbench.colorTheme": "Default Light+",
    "editor.fontSize": 16,
    "editor.minimap.enabled": false,
    "terminal.integrated.defaultProfile.windows": "PowerShell",
    "liveServer.settings.donotShowInfoMsg": true,
    "vetur.validation.style": false,
    "vetur.format.options.tabSize": 4,
    "files.associations": {
        "*.liquid": "html"
    },
    "[html]": {
        "editor.defaultFormatter": "vscode.html-language-features"
    },
    "liquid.format": true,
    "[css]": {
        "editor.defaultFormatter": "aeschli.vscode-css-formatter"
    },
    "redhat.telemetry.enabled": true,
    "liveSassCompile.settings.autoprefix": [],
    "[liquid]": {
        "editor.defaultFormatter": "vscode.html-language-features"
    },
    "liquid.format.json": {
        "arrayFormat": "default"
    },
    "editor.formatOnSaveMode": "modifications",
}`

**Comment by panoply** [comment]
Hey,

You have incorrect settings defined.
 
It is really important that you **read** and go through the [readme](https://github.com/panoply/vscode-liquid). I know that can be annoying but it will give you best oversight and understanding. The [**v3.0.0**](https://github.com/panoply/vscode-liquid/releases/tag/v3.0.0) release notes also go over all these changes.

Anyway, here is what you need:

```jsonc
{
    "files.associations": {
          // Don't do this anymore
         // "*.liquid": "html" 
    },

    // This is no longer valid, as per the release notes
    // "liquid.format": true,

    // Use this to enable formatting
    "liquid.format.enable": true,

    // add these settings have the extension format Liquid
     "[liquid]": {
      "editor.defaultFormatter": "sissel.shopify-liquid",
      "editor.formatOnSave": true
    },
    
    //  You are associating a completely different formatter for liquid, so beautification will not work. 
    //  You need to remove this
    //    "[liquid]": {
    //        "editor.defaultFormatter": "vscode.html-language-features"
    //    }
}
```

**Comment by onderakbulut** [comment]
I tried your suggestion but not solved problem.
Can you share your valid settings.json file ?
Thanks!
