### ISSUE TITLE
`forloop.index0` syntax highlighting

### ISSUE THREAD

**Issue by davidwarrington** [panoply/vscode-liquid#113]
I don't know if this is intentional, and it's not a huge problem for me either way, but I've just spotted `index0` has different colours for `index` and `0`. Personally I actually kinda like it but I still think it's a bug?

![image](https://user-images.githubusercontent.com/9138568/193859089-e51d2f2e-ae04-4683-9478-4e91be3feaa3.png)

**Comment by panoply** [comment]
Shipped https://github.com/panoply/vscode-liquid/pull/110
