### ISSUE TITLE
VSCode claiming the Liquid extension cannot format 'Liquid'-files

### ISSUE THREAD

**Issue by t3pfaffe** [panoply/vscode-liquid#114]
Getting the following error on liquid files in VSCode with the latest version of the extension. `Formatting - Extension 'Liquid' is configured as formatter but it cannot format 'Liquid'-files`.

<img width="377" alt="liquid-ext error" src="https://user-images.githubusercontent.com/16065962/194115383-f55af447-5457-41ba-bb20-91e766fff07a.png">

**Comment by t3pfaffe** [comment]
I was able to replicate it earlier but it does now seem like its resolved itself. I will update if I am able to get it to show up again.

**Comment by spam0115** [comment]
It is happening to me now.
