### ISSUE TITLE
Liquid formatting issues

### ISSUE THREAD

**Issue by t3pfaffe** [panoply/vscode-liquid#115]
Listing all the issues I currently have with the liquid auto formatter in the recent update. I can break it down into smaller issues when I get more time in the future if desired.

I have a format that I use for my liquid comment documentation. Upon saving with 'format on save' enabled the closing `{% endcomment %}` tag gets merged onto the last line inside the comment block and any indents inside the comment block get overwritten and removed as well. Is there any way to have the formatter ignore any of the text inside comments? It is fairly annoying and ruins the established documentation formatting I have across my codebase. Example below:

```
{% comment %}
Info/Nav Header Section:
- Primary header section with info/quicklinks bar and
   navigation bar.

@author t3pfaffe
{% endcomment %}
```
gets formatted to:
```
{% comment %}
  Info/Nav Header Section:
  - Primary header section with info/quicklinks bar and
  navigation bar.

  @author t3pfaffe{% endcomment %}
```

----

In addition `<script>` tags seem to get erroneously moved onto the same line as any liquid tag above it. Example below:
```
{% endstyle %}

<script>
```
gets formatted to:
```
{% endstyle %}<script>
```

---
Also any indents of CSS in `{% style %}` or `{% stylesheet%}` tags gets removed even for those nested in @media blocks.

---
Additional side note not pertaining to the formatter: is there any way to get the `{% schema %}` tags to allow folding by JSON objects? Its very annoying to work with all these large blocks that I cant hide away to avoid distractions. I think it makes sense for all of the large multi-line liquid tags to allow folding to begin with. Is there a setting for it I am missing?

**Comment by panoply** [comment]
Should be resolved in https://github.com/panoply/vscode-liquid/pull/110 (Latest version)
