### ISSUE TITLE
Solving `ERROR: Deprecated configuration provided in workspace`

### ISSUE THREAD

**Issue by MattBudz** [panoply/vscode-liquid#116]
It seems that with v3 we now have a `.liquidrc` file for settings.

I can't justify pushing this file to my product's github repo since not all of the devs use VSCode. Additionally, the product's users shouldn't have this file in their cloned repo since it doesn't have anything to do with the functionality of the product. I also don't want to have to generate a `.liquidrc` for each new project I'm working on.

Is there a way to add these generated settings to the global user/workspace settings? The settings file I'm referring to is located (macOS): `~/Library/Application Support/Code/User/settings.json`. I like the settings generated by `Liquid: Generate .liquidrc (recommended)` but I'd love a way to set this once and have it apply to all of my projects in VSCode.

Am I missing something in the docs? Any help/direction would be greatly appreciated. As always, keep up the great work!

**Comment by MattBudz** [comment]
Ahh found my answer in the release notes: https://github.com/panoply/vscode-liquid/releases/tag/v3.0.0

I removed the old 2.3.0 settings and pasted in:
```json
    "liquid.engine": "shopify",
    "liquid.config.baseUrl": ".",
    "liquid.settings.target": "workspace",
    "liquid.completion.tags": true,
    "liquid.completion.objects": true,
    "liquid.completion.filters": true,
    "liquid.format.enable": true,  //  instead of "liquid.format": true,
    "liquid.format.ignore": [],
    "liquid.format.wrap": 0,
    "liquid.format.indentSize": 2,
    "liquid.format.endNewLine": false,
    "liquid.format.commentIndent": false,
    "liquid.format.preserveLine": 3,
    "liquid.format.preserveComment": false,
    "liquid.format.crlf": false,
    "liquid.format.markup": {},
    "liquid.format.script": {},
    "liquid.format.style": {},
    "liquid.format.json": {},
```

all is good now, nevertheless, it would be awesome if there was a generate recommended settings option that adds the settings in to the user/workspace settings.json.

**Comment by panoply** [comment]
Hey @MattBudz,

I can look into adding a completion block within workspace settings. I wouldn't want to generate the workspace files. The `.liquidrc` will become a lot more important as the extension being to transition into Liquify. 

I'll keep this open, but any additional thoughts/feedback are always appreciated.

**Comment by Franklonchas** [comment]
Hello,

I have a "similar to this" error, I have updated the plugin in vscode, and also changed my settings.json to be able to work with the new settings but unfortunately it doesn't work for me. I had to go back to version 2.3.0.

What is wrong with me or what am I missing?

**Comment by panoply** [comment]
Closing this as it seems stale. Open new issue if you need any help.
