### ISSUE TITLE
Schema Snippets not working

### ISSUE THREAD

**Issue by jzelaya-manduka** [panoply/vscode-liquid#118]
I've just installed this plugin and saw in the README that schema snippets are supported, but they don't seem to work in a Shopify theme project. Tried writing the schema in a JSON file and in a Schema tag in a sections/.liquid file and no luck.

**Comment by muchisx** [comment]
@panoply If I'm correct this is coming back in #110 right?

**Comment by panoply** [comment]
@muchisx correct! Shipped in https://github.com/panoply/vscode-liquid/pull/110
