### ISSUE TITLE
formating removes indention from shema section

### ISSUE THREAD

**Issue by reco** [panoply/vscode-liquid#12]
before formating

```
{% schema %}
{
  "foo": "bar"
}
{% endschema %}
```

after formating
```
{% schema %}
{
"foo": "bar"
}
{% endschema %}
```

this is may settings for schema

```
...
"schema": {
  "indent_size": 2,
  "format_array": "indent"
}
...
```

**Comment by Mindgames** [comment]
@reco Did you solve this?  Did run in to same issue

**Comment by panoply** [comment]
Hey guys, I will have a look into what is causing the issue this week. I don't seem to have a problem, see screencast:

Do you have any other formatters running or other extensions?

<img src="https://user-images.githubusercontent.com/7041324/59290678-68e0b880-8c79-11e9-8f05-920de1bbf2c9.gif" width="50%">

**Comment by panoply** [comment]
If you have any HTML formatter extensions or linters in your VS Code setup I would assume they would be causing the issue. Can you try eliminating to formatting `schema` rule from your VS Code settings?

**Comment by panoply** [comment]
Closing. This issue is unrelated to the extension. Check if another extension is handling formatting.
