### ISSUE TITLE
Autoformat adding additional characters on save

### ISSUE THREAD

**Issue by brady-sewall** [panoply/vscode-liquid#120]
For example, if I have a liquid file with:
```
<div>
    <ul class="overflow-y-scroll">
        {%- 
                 render 'global-nav-list', 
                 menu_item_class:'global-nav__menu-item relative my-xs overflow-y-hidden', 
                 menu_base_button_class:'text-h3 md:text-l-h3',
                 menu_base_link_class:'text-h3 md:text-l-h3', 
                 submenu_wrapper_class:'global-nav-mobile__menu-item-with-subitem opacity-0 overflow-y-hidden max-h-0 ml-xs mt-0 mb-0 z-10 space-y-1' 
               -%}
        {% 
                 render 'global-nav-cart-button', 
                 class: 'global-nav__cart-button relative mt-xs w-10 h-10 rounded-full border-neutral-300 border flex items-center justify-center',
               %}
      </ul>
    </div>
```

When I save the file, it adds an extra > to the last closing div
```
</div>>
```
Which breaks the code/layout

**Comment by machancock** [comment]
I'm having this same issue, I've had to disable the extension for the time being.

**Comment by freshwater-dev** [comment]
Happening for me as well, and just keeps on adding an extra one after each save, so it could be </div>>>>>>

Also getting an extra " } " in the closing the schema tag for .liquid files:

`{% endschema %}}}}`

**Comment by panoply** [comment]
Hey guys!

Fixed in the latest release **v3.1.0**

**Comment by brady-sewall** [comment]
> Hey guys!
> 
> Fixed in the latest release **v3.1.0**

Amazing and thank you! Is there a way to manually use v3.1.0 until the official version is released on the VSCode Marketplace?

**Comment by panoply** [comment]
It should be available to consume on Marketplace. You will likely need to restart editor. Let me know how you go.

**Comment by brady-sewall** [comment]
> It should be available to consume on Marketplace. You will likely need to restart editor. Let me know how you go.

Again, thank you so much! This extension is a lifesaver.
