### ISSUE TITLE
comments_enabled? not supporting format / syntax highlighting

### ISSUE THREAD

**Issue by outerpreneur** [panoply/vscode-liquid#125]
``![Screen Shot 2022-11-03 at 12 23 03 PM](https://user-images.githubusercontent.com/91225228/199709101-5d71e3c0-d3d5-4715-8f91-6f90a3e0252e.jpg)

When I type comments_enabled, the formatter doesn't support my code anymore

`
{% if blog.comments_enabled? %}
  <div id="comments" class="my-8">
    {% if article.comments_count > 0 }
      {% else
    %}
      There are no comments in this article
    {% endif %}
  </div>
{% endif %}`

**Comment by panoply** [comment]
Good find! 

Will apply patch.

**Comment by artfusion** [comment]
Hi Agreed yes this has also been my experience. It is being talked about on the udemy course
<img width="698" alt="image" src="https://user-images.githubusercontent.com/1841669/201073328-27778419-1e44-4529-875e-adffb71423b9.png">

**Comment by panoply** [comment]
Shipping in **3.1.2** (this week)

**Comment by panoply** [comment]
Sorry for the delay here, a lot more went into this version. Instead of pushing a patch this will be fixed in the next minor **3.2.0** - awaiting some final tests. I'll close this as [76db954](https://github.com/panoply/vscode-liquid/commit/76db9546d9ffd1d6301262844071ebef0e8c2cfb) solved it anyway.

**Comment by panoply** [comment]
Re-opening this one as per #137 the issue still persists but in different structures.

**Comment by syf107** [comment]
Hello, I found this and still have a problem with the comment. It's still read as reserve word of comment tag and commenting to the bottom of the code.  I'm on the latest version of this extension 3.2.2 on vscode.
![image](https://user-images.githubusercontent.com/48479350/216260172-b77d3fef-2e35-426c-9749-05a68c4f2c16.png)

**Comment by panoply** [comment]
Shipping in #138 – Available tomorrow.
