### ISSUE TITLE
Schema Snippets isn't working inside {% schema %} instead outside it is good. how to fix it.

### ISSUE THREAD

**Issue by SELFecomm** [panoply/vscode-liquid#126]
ref: https://github.com/panoply/vscode-liquid#schema-snippets

Outside schema tags its working fine:
![image](https://user-images.githubusercontent.com/109971353/199783073-d964aac2-5954-44c9-ba3b-700e824120ec.png)

Inside Schema it is not working:
![image](https://user-images.githubusercontent.com/109971353/199783299-57a488fa-783e-4eef-85ce-bddd464b91d9.png)

How do I fix it?

**Comment by panoply** [comment]
Hey @SELFecomm 

This will be addressed in #121

**Comment by panoply** [comment]
I'll be deprecating schema snippets as the Liquify supersede provides this. Until Liquify is released, schema snippets will not be supported by the extension.

**Comment by panoply** [comment]
Moving this to #121 where deprecation of schema snippets with replacement for intelliSense completions capabilities will be made available.
