### ISSUE TITLE
Formatter doesn't work with part like "---"

### ISSUE THREAD

**Issue by danny1ng** [panoply/vscode-liquid#129]
Formatter don't work with "---". Prettify ignore also not work for me. 

```
{% comment %} @prettify-ignore-start {% endcomment %}
---
{% comment %} @prettify-ignore-end {% endcomment %}
```

if you delete this part then everything works.

[Video with issue](https://monosnap.com/file/gwpJIbvNMcjfiR3hBjC7P0xqx2NaHp)

[Playground](https://liquify.dev/playground/prettify#M=N4Ig9gDgLglmB2BnEAuUAbAhvA5gV0xwFNUR0YBHPGAExABoQoALIgWxJRAjFgQZAAjTIiIAFTC1IA6AcxHNUUAE54ijTOnRgA7gGUiUWLmQoAZptGMzYZW0lLV6kDbuSA8vD2YAbpxVqjADGYGw88ETwUKagEToAYjDonPB4WgC+6YxsYDScIJhBRAD0OXnFUEQAHlACENj5iBDktYxYuATEpJU1AoiYYcmoqVoaeFBgACKGREG15pbO7fiERAByA-liWDDwAAQAKtWtIIhQkjEgQfLKhZXKADKROFJcAIz0AMwAHN97AMI3O5EZTINrYFbEDYcUjbTC7Q7HPowABeRHcZkSQ3e0gALHsANIAITqykMsDMAE8DjAYVx4rZ7EYiDQAGTwQRNADcu3ZnIgXIADNJBWxkFkQLsIONSMAAKQAWj2ITYHCiewVcvSewAAhAyUYYFSFTAcPBbEQFWdMMooHt5UrIjQVWq7Zr0gAdZQe+AKv1en0O5WhV0arW6-Xko2Uk1mi0Kp32xV7J0uyJurUB+BZ+V7RDXdiYPaZ73wYBZvaVquVj0geCbWsoPa1gASREweW9DArzclIWzqF7tNWAH0elBa-QezXTlGTI29gBtaf2lcz2gL2uwKDJSdr3tYQREdCbkA0ndEPel6szqCUiCXwe1s7KXY4WsrrIr8vXm+1jdPiAeT5q+0BwAOU6-tWtaHsep7TCBMBgQgV4+jevZ3g+p7jqh+xVtqVbfvu-40KewhBAA1jgyhgHg8A0COw7ELh6EwZgR4noBRKFFRNF0TQexMY+kFoX+TD3o+Tb-vYxAjhAMCUSCLH4dBv4ALoiXhtaCNolGIAui4aT2z6zHwSAjv2lRRAuP6iTOrAdkpg62Xh0Gzoa87Oc2UFiduu6AQAamA6B4NAIjBkgRBUJIeDKHsmiUNQAlBHgbBUEQ0jKaxQFEIhyEDlJIAAKp2tFiDxQJkB8Jl3Y+W55G8bR9GMTJkm9sU-SDLlxRCYgxR5BYaRQNIiA+O+ID7l+PnabpFH6YOhmfj2nqlitgZyim9H5qw9jFmt2algAPDQMA+IJNAALy1sAwB5qZ4HSNg1y2IxAmZLWypYIgiBXSADmdla90oSA9q3aIcwPbpoS8KdRAjpIKgwII4y5XsmQAHw9odzAAEzowYEMIHsTZto5yiHcUuOY7+2N44gNBFiIAlM0z8X02zzPs6zrNZiux2ndTdlViz9NM1mFMnT4gt4RTVO86WWPMMoxTS4rnz43OOCILL6vy6J-NSzdd2E-AI2a4g0h+UQaPpBLAt6zLkvo0b4NmWbHla9IwFBKBZk23bUtYxA6OHbSOB5soQS-S7QOm6IHsWw11FNQxQk2x9KsU8HDs1kd-X2wrhc+g7JdFwdxdl6XFfV+XtdV3XleNzX9ct03DfN23rcd937e913fed4PNcCLRUDSvMIC5tthZ7aJ5aub29YcKepOdnuC--v2p5CWOxzr258fGFrBlC5W8-oeupGAVb+8X2xHGnue-lTgvbmYW1z6I7gH6v2j9Crr-S+p5va+3ArfbKsFOKFQQj7JCZlwG+QkthPeE1f7anPnfSUV9CpJz4s1ISCC3KQNPNxSiyd+KCVaoQwi4ksKAR3vJRSXZT5oyFkZDeQhZrzSbIZF+B9Y6IAsggKyE5nIsNrP9JyTYMHZUPm+bhACL40JvoFYKoVzjlX7KIaKUBYrxXIFQWgypUrpRqnwpRvYQFwLAYBEqewyoVT2FVOAZiWH1R4uQ-BVDAIdQGM0bqvV+pEEGugYao1xpuL-pEmaYA9IGTUiwz0C8kmViSbmJ009dqZmzPAA251o5g1jo9eAz1lCvXTiDIIX0foSPbADV2NjeyFJNtIKGORYB+HhkYV8yNKjlU9CATGMsqYEz9iTOpIJZZ431lTUWHMObcy5kszmKzi4LwNkM9CIsGb0yFgHTZewplDLWZWbGytjnDPVgYBOOsLmnKdjHFpciTCWxgBedOMt86BxyfcgWjy3bPM9lY-KHzTlfIOYdYOoc2Dh0QJHApxsAXm2kLglOLVVgVMzsUbOOSfT7JAOkIAA)

**Comment by panoply** [comment]
@megaDannyIng Good find. Will get this fixed in next Prettify patch - Thanks for using the Playground and being informative here. I appreciate it. 🙏🏼

**Comment by panoply** [comment]
Will try get this out for **v3.2.0** but if not will be sure to fix in a patch.

**Comment by panoply** [comment]
Shipping in **3.2.0**
