### ISSUE TITLE
How do I properly configure workspace for *.html files?

### ISSUE THREAD

**Issue by anantakrishna** [panoply/vscode-liquid#131]
I'd prefer my liquid templates to have `*.html` extension. How do I properly configure VS Code in this case? Note: I'm using `prettier` and `@shopify/prettier-plugin-liquid` for formatting instead of built-in formatting of this extension.

This is my attempt.

```
{
  "files.associations": {
    "*.html": "liquid"
  },
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "[liquid]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "editor.formatOnSave": true,
  "liquid.format.enable": false,
  "liquid.engine": "standard",
}
```

Main thing is `files.association`, I guess. Is my approach correct?

Extension v3.1.1

**Comment by panoply** [comment]
Hey @anantakrishna 

This is the correct configuration. Are you having trouble configuring Prettier to run on the file?

**Comment by panoply** [comment]
Just out of curiosity, is there any specific reason for using a `.html` over a `.liquid`- is there a feature missing per-say?

**Comment by anantakrishna** [comment]
> Are you having trouble configuring Prettier to run on the file?

No, it runs fine. I just was puzzled because in October the Liquid extension would highlight the syntax etc in the HTML files without this `files.association` setting (as far as I remember), but now when I opened the project again, the extension features were not active in the HTML files. That is why I had to configure files association. Maybe it's due to extension upgrade to v3?

> Just out of curiosity, is there any specific reason for using a `.html` over a `.liquid`- is there a feature missing per-say?

We're using the Liquid template language in the 11ty project. There, [HTML files can be optionally pre-processed with an additional template engine](https://www.11ty.dev/docs/languages/html/#:~:text=HTML%20files%20can%20be%20optionally%20pre%2Dprocessed%20with%20an%20additional%20template%20engine), which is [Liquid by default](https://www.11ty.dev/docs/config/#default-template-engine-for-html-files). My templates are mostly plain HTML with sprinkles of Liquid, that is why we considered right to keep the `html` extension for the files. This is the only reason.

**Comment by panoply** [comment]
So in previous versions the extension would use injection grammars are extend HTML. This was a little problematic in a lot of cases. As of v3^ Liquid is considered as an official language and HTML features like completions, highlighting and all the rest are still respected in a `.liquid` file. 

> We're using the Liquid template language in the 11ty project

I am looking to improve features for 11ty and static site generated projects that employ Liquid as the template language. I'd love to learn more about any wishlist capabilities/features you wish were available. In future versions one of the main capabilities I aim to bring is auto-completion support for data contained in frontmatter. I also believe bringing support for _collection_ based data would be a great benefit. 

Any thoughts or feedback would be greatly appreciated, thanks.

**Comment by anantakrishna** [comment]
Thanks for confirming my guess. After reading v3 release notes I suspected that something changed in handling `*.html` files :)

As of now in our case I haven't experienced any lack of features or misbehaviour. Should I face any issue, I'll let you know, keeping in mind your kind invitation!
