### ISSUE TITLE
Formatter adding whitespace to JS string

### ISSUE THREAD

**Issue by davidwarrington** [panoply/vscode-liquid#133]
Formatter adds space after Liquid tag inside JS string. I've not made any configuration changes so this is using the default settings.

I have the following code:

```liquid
<script>
  document.body.style.setProperty('--pg-MobileReassurances-fontSize', '{{ section.settings.font_size }}px');
</script>
```

After saving it becomes the following and breaks existing CSS because of the whitespace it has introduced:
```liquid
<script>
  document.body.style.setProperty('--pg-MobileReassurances-fontSize', '{{ section.settings.font_size }} px');
</script>
```

**Comment by panoply** [comment]
This one is solved in #138
