### ISSUE TITLE
Schema formatter does not support localised inputs

### ISSUE THREAD

**Issue by ccanete** [panoply/vscode-liquid#135]
When using localised name, content, label or info, it is not recognised by the schema formatter:

![Screenshot 2022-12-13 at 09 59 13](https://user-images.githubusercontent.com/9353672/207273251-6c07be05-b652-40dd-b668-44978f5dd99f.png)

**Comment by panoply** [comment]
Hey @ccanete 

Thanks for submitting this. I'll get a patch out today for this.

**Comment by panoply** [comment]
No problems. I don't leverage locales, if it is not too much trouble for you, can you shoot me a list of properties which can contain locales?
