### ISSUE TITLE
Toggle line comment doesn't work

### ISSUE THREAD

**Issue by SHiLLySiT** [panoply/vscode-liquid#139]
I'm not sure if this is a bug, or a configuration issue on my end, but I can't seem to figure out how to get the **Toggle line comment** shortcut working in Liquid files. Using the shortcut key or command does nothing.  However switching the language mode to HTML causes **Toggle line comment** command to work again, but then the syntax highlighting is wrong and I lose Liquid intellisense.

**Comment by panoply** [comment]
Hey @SHiLLySiT 

Interesting, can you give me some more information? What is the command sequence you use?

**Comment by SHiLLySiT** [comment]
@panoply Do you mean the keyboard shortcut? I have it mapped to CTRL+/ which I think might be the default.

**Comment by panoply** [comment]
Yeah, this should be working. I am on a Mac though. I'll do some investigating. @toklok can you try this on your machine?

**Comment by toklok** [comment]
> Yeah, this should be working. I am on a Mac though. I'll do some investigating. @toklok can you try this on your machine?

I'm seeing the same thing, I do remember it working though, i'm unable to do `Command + /` to comment some code 

`{% if true%}  {% endif %}` if I do `Cmd + /` I would expect the outcome to be `{% comment %}{% if true %} {% endif %}{% endcomment %}`

**Comment by brettwbyron** [comment]
I'm also having the same issue. My `Cmd + /` nor command pallet do anything. Any updates on this?

**Comment by anantakrishna** [comment]
Let me add that it's not only about commenting Liquid code, but plain HTML in the liquid files, too. My use case: to add documenting comment into a line above an element. I usually add am empty line and hit `Ctrl+/` to make it a comment (i.e. `<!-- -->`) and type some text there.

**Comment by elburro1887** [comment]
I am having the same issue, when trying to comment via CMD + / on Mac. Works neither in JS or HTML parts of the file.

**Comment by panoply** [comment]
🚢
