### ISSUE TITLE
import asset breaking JS syntax hightlighting

### ISSUE THREAD

**Issue by davidwarrington** [panoply/vscode-liquid#140]
I'm having to write an inline script and the import syntax combined with a Liquid tag has broken highlighting

It seems full imports specifically that are causing an issue for me
```js
import {{ 'file.js' | asset_url | json }}
``` 

![image](https://user-images.githubusercontent.com/9138568/209180064-b9c33aaa-7f58-4ef3-84bb-3c42f8922e55.png)

Replacing the `json` filter by wrapping the liquid tag in quotes resolved the issue for me, I just prefer to use `json` if possible because I expect that it's safer (although now I think about it I'm unsure if it is in this context).

![image](https://user-images.githubusercontent.com/9138568/209180503-8b88bc57-16cb-4b95-898d-065609ea1bad.png)

It's probably not a high priority issue regardless but figured I best report it

**Comment by panoply** [comment]
Good catch. Will have it fixed for #138 - Some works needs to be done on the injection grammars for embedded regions. This is a good opportunity to refine that.

**Comment by panoply** [comment]
@davidwarrington https://github.com/panoply/vscode-liquid/commit/65cbb2859e0ce3de3960b63093c490ff71499e66 will fix this. I definitely need more samples of Liquid being is being infused within embedded languages. This was a really great use case scenario.
