### ISSUE TITLE
New auto-format on save is causing issues

### ISSUE THREAD

**Issue by customerhub** [panoply/vscode-liquid#141]
I format my liquid very specifically to optimize size for Shopify app extensions - this new feature you added by default that formats on save, is a nightmare for us - it is messing up all our optimized formatting. 

I tried toggling it off (with that little liquid icon at the bottom) but it continues to format on save and undo my changes, even after restart.

Can you please let me know what the killswitch is for this thing? and how exactly I toggle it? (ie is it a Command Pallette command?).

I will be uninstalling this one until you advise - and just a recomentation - do not auto-enable such features by default that mess with code format so aggressivlely, alert us to the feature and how we can enable if we choose too.

**Comment by panoply** [comment]
> I format my liquid very specifically to optimize size for Shopify app extensions - this new feature you added by default that formats on save, is a nightmare for us - it is messing up all our optimized formatting

As per the documentation [Settings Default Formatter](https://github.com/panoply/vscode-liquid#setting-default-formatter) you can prevent formatting on save as follows:

```jsonc

{
   "[liquid]": {
      "editor.formatOnSave": false
   }
}

```

> - and just a recomentation - do not auto-enable such features by default that mess with code format so aggressivlely, alert us to the feature and how we can enable if we choose too.

Just a recommendation, maybe take the time to read about vscode how to control the editor. As Per #132 the next release addresses the defaults applied.

**Comment by panoply** [comment]
Closing this, see #142  for further details.
