### ISSUE TITLE
Comment in Liquid tag inside HTML attribute breaks syntax highlighting

### ISSUE THREAD

**Issue by sentience** [panoply/vscode-liquid#147]
This code incorrectly renders the closing `%}` of the comment tag in the comment style, and breaks HTML syntax highlighting in the rest of the file:

```html
  <div
    class="
      page-inset-padding flex
      {% # arrow overlaps preceding margin %}
      -mbs-4 pbs-4
    "
  >
```

**Partial work-around:** Removing the space after the `#` keeps the syntax highlighting in the rest of the file working, but does not highlight the comment as a comment:

```html
  <div
    class="
      page-inset-padding flex
      {% #arrow overlaps preceding margin %}
      -mbs-4 pbs-4
    "
  >
```

**Comment by panoply** [comment]
@sentience Interesting structure. 

I can likely augment the grammar injection for value highlighting. Good catch and thanks for reporting these issues, it is a huge help and greatly appreciated.
