### ISSUE TITLE
{% javascript %} open liquid tag not being well scoped

### ISSUE THREAD

**Issue by muchisx** [panoply/vscode-liquid#149]
Hey, hope all is going great!

The last characters of the {% javascript %} tag aren't being recognized as the end of the tag as you can see in this image:
![image](https://user-images.githubusercontent.com/34131801/212751117-7ee98b02-5090-4e83-9f91-def7304a8467.png)

A well recognized tag just for comparaison:
![image](https://user-images.githubusercontent.com/34131801/212751276-676a8665-028a-4814-a291-2921f6493aa5.png)

Also, as a side note, I'm not getting JS autocompletion inside this tag or CSS autocompletion inside the {% stylesheet %} or {% style %} tags, do you know if its possible to acheive this in the future?
Like extending the behaviour of HTML when you create a <style> tag you get CSS autocompletion and a <script> tag you get JS autocompletion, would be awesome!

**Comment by panoply** [comment]
Hey @muchisx 

So I will expose support for CSS / SCSS IntelliSense but introducing IntelliSense for JS is a little more difficult to employ, though it is something that will be available in the future.
