### ISSUE TITLE
 The "comment" keyword in the code makes the next code color the same as the actual comment color.

### ISSUE THREAD

**Issue by haroldao** [panoply/vscode-liquid#152]
c.f. this Issue => https://github.com/Shopify/theme-check-vscode/issues/109

**Comment by panoply** [comment]
This is addressed in #138 and shipping in next release. Also see #125. 

> **Note**&nbsp;
> There is no need to hard-reference issues in github. Sub references are automatically applied. Doing this, just create noise in projects which are already busy. 
>

**Comment by haroldao** [comment]
got it 👏🏽😉!
