### ISSUE TITLE
1 more end type than start type - block tag

### ISSUE THREAD

**Issue by Daniel-Knights** [panoply/vscode-liquid#153]
Formatting this:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta
    http-equiv="X-UA-Compatible"
    content="IE=edge"
  >
  <meta
    name="viewport"
    content="width=device-width, initial-scale=1.0"
  >
  <title>Document</title>
  <link rel="stylesheet" href="custom.css" />
</head>
<body>
  {% block %}{% endblock %}
</body>
</html>
```

Results in this:

```
ERROR: Parse error occured when formatting document

Prettify Error (line 18):
1 more end type than start type
```

If I remove `{% block %}{% endblock %}`, it formats fine.

Extension version 3.2.2.

**Comment by panoply** [comment]
Hey @Daniel-Knights 

I will have a look at this, but I believe it is addressed in #138. Can you try adding content within the `{% block %}`?

**Comment by Daniel-Knights** [comment]
Hi, thanks @panoply. I tried with content, but get the same result

**Comment by panoply** [comment]
I'm not sure of the exact issue, but likely related to `<body>` containment. It definitely addressed and fixed in #138 - however I still need to tie up some loose ends before it is shipped. If it possible for you execute that code in an isolated manner, like within an `_include` or `snippet` file where it is not encapsulated within a `<body>` element?

**Comment by Daniel-Knights** [comment]
It does format, but the indentation isn't right:

```html
<!DOCTYPE html>
      <html lang="en">
        <head>
          <meta charset="UTF-8">
          <meta http-equiv="X-UA-Compatible" content="IE=edge">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>Document</title>
          <link rel="stylesheet" href="custom.css" />
        </head>
        <body>
          {% render "block" %}
        </body>
      </html>
```

Also, the `block` tag doesn't work as it should when moved to a separate file, but that's not really relevant here.

**Comment by panoply** [comment]
This one is really stale but is was fixed some time ago!
