### ISSUE TITLE
Liquid CSS code formatting

### ISSUE THREAD

**Issue by Muhammad-Jawad133** [panoply/vscode-liquid#154]
I have an swear issue using this extension. so You can see in attached screenshot.
when I am installing this extension and enable it's messy my all CSS code in liquid file.
please suggest me to fix it and help me.
I am trying but not able to fix it.
I have deleted all of my other extensions and use this extension alone but it's still doing the same.
Please help me. now I have disabled tis extension form my vs code.
Loom video also attached
https://loom.com/share/a0518dc97a07466e974dab169710565f

![image](https://user-images.githubusercontent.com/88041880/222990662-c14bf497-65d4-4722-b923-4401814cbdc8.png)

![image](https://user-images.githubusercontent.com/88041880/222993441-86830da5-b812-475e-86ba-b20f8621acc0.png)

**Comment by ianjwhitmore** [comment]
Had the same exact issue today and had to uninstall.

**Comment by Muhammad-Jawad133** [comment]
> Had the same exact issue today and had to uninstall.

yeah ianjwhitmore I am too much worried about it.
I don't know how to fix it.
this extension published by Shopify.dev .

**Comment by panoply** [comment]
Hey guys, 

Patch is coming in #138 - You can always ignore these files, in the `.liquidrc` file:

```json
{
   "ignore": ["./path/to/file.css"]
}
```
When you want disable formatting altogether, In your workspace settings:

```jsonc
  "[liquid]": {
    "editor.defaultFormatter": "sissel.shopify-liquid",
    "editor.formatOnSave": false // Make this false
  },
```

This will turn off formatting.

**Comment by Muhammad-Jawad133** [comment]
> Hey guys,
> 
> Patch is coming in #138 - You can always ignore these files, in the `.liquidrc` file:
> 
> ```json
> {
>    "ignore": ["./path/to/file.css"]
> }
> ```
> 
> When you want disable formatting altogether, In your workspace settings:
> 
> ```js
>   "[liquid]": {
>     "editor.defaultFormatter": "sissel.shopify-liquid",
>     "editor.formatOnSave": false // Make this false
>   },
> ```
> 
> This will turn off formatting.

Hey panoply, Thanks to help me.
but if I will do like this so I will have to add this code for everytime for every css.liquid file,
if I write css code in any liquid file, it will auto format the code and mess my css code in every liquid file.

**Comment by panoply** [comment]
@Muhammad-Jawad133 Ah, I see. In that case you can just disable formatting for `liquid-css` language in you vscode workspace settings:

```json
 "[liquid-css]": {
    "editor.defaultFormatter": "sissel.shopify-liquid",
    "editor.formatOnSave": false // Make this false
  }
```

**Comment by Muhammad-Jawad133** [comment]
> @Muhammad-Jawad133 Ah, I see. In that case you can just disable formatting for `liquid-css` language in you vscode workspace settings:
> 
> ```js
>  "[liquid-css]": {
>     "editor.defaultFormatter": "sissel.shopify-liquid",
>     "editor.formatOnSave": false // Make this false
>   }
> ```

@panoply  Thank you very much, should I paste this code in user settings == settings.json?

**Comment by Muhammad-Jawad133** [comment]
> Yeah, that will work. You can also use a `.vscode/settings.json` file. However user settings should work too.

@panoply 
![image](https://user-images.githubusercontent.com/88041880/223574941-3ee9479e-5bc0-4103-974a-cfb784c43d53.png)

I did exactly like you said but my I have still the same issue.
that code you have provided me that works for only liquid.css file, but sometime when I write style code in my liquid file or JavaScript code in liquid file then this extension messing my that CSS or JS code in every liquid file.

**Comment by Muhammad-Jawad133** [comment]
> > Yeah, that will work. You can also use a `.vscode/settings.json` file. However user settings should work too.
> 
> @panoply ![image](https://user-images.githubusercontent.com/88041880/223574941-3ee9479e-5bc0-4103-974a-cfb784c43d53.png)
> 
> I did exactly like you said but my I have still the same issue. that code you have provided me that works for only liquid.css file, but sometime when I write style code in my liquid file or JavaScript code in liquid file then this extension messing my that CSS or JS code in every liquid file.

you can see in the attached screenshot.

**Comment by panoply** [comment]
Hey, so this is all listed in the readme file and I ask you to please read it. Use the following settings to disable in other files:

```
{
  "[liquid]": {
        "editor.defaultFormatter": "sissel.shopify-liquid",
        "editor.formatOnSave": false // Make this false
  },
  "[liquid-css]": {
        "editor.defaultFormatter": "sissel.shopify-liquid",
        "editor.formatOnSave": false // Make this false
  },
  "[liquid-javascript]": {
        "editor.defaultFormatter": "sissel.shopify-liquid",
        "editor.formatOnSave": false // Make this false
  }
}
```

**Comment by panoply** [comment]
Also, `{% style %}` tags are only partially supported. You will need to digest and understand the formatting rules to apply in order to get you preferred results.

**Comment by Avnsx** [comment]
same issue here with formatting, even if i do the smallest 1 letter change and save my theme.liquid it messes up the entire formatting and bricks my website

**Comment by Avnsx** [comment]
> disable formatting for `liquid-css` language in you vscode workspace settings

then what is the point of using your extension in first place, if i disable one of the most important features i installed it for?? 🤣

**Comment by panoply** [comment]
@Avnsx this is likely due to the infusion of CSS together with Liquid code. You can either contribute to the conversation in a productive manner or simply don't use the extension. If you can do better, please go right ahead and PR.

**Comment by panoply** [comment]
@jackchristian1995 Can you send me the code sample?

FWIW if you can run the CSS within code blocks, eg: 

```
{% style %}
 :root {
    --max-content-width: {{ settings.max_content_width }}%;
 }
{% endstyle %}
```
In the Æsthetic Playground and then press `cmd+s` it would help me understand issues occuring for the 4.0.0 release:

https://æsthetic.dev/playground/

**Comment by panoply** [comment]
Solving in #138 – Shiping tomorrow.
