### ISSUE TITLE
vscode liquid format on save adds new tabs

### ISSUE THREAD

**Issue by itszoose** [panoply/vscode-liquid#158]
Hello! 

My issue is exactly as I previously described in issue #96.  Whenever the x-data attribute has empty lines it just keeps on adding and identing the code on every save.

I am not sure why it's behaving like this, I searched everywhere for days and I was forced to jump to Webstorm for a few months now but I really want to use vscode. 

Any help on this matter is greatly appreciated. 

https://github.com/panoply/vscode-liquid/assets/18335079/8011a751-3eb6-4db8-9d8d-fdfa8b7bdfbd

**Comment by panoply** [comment]
Hey @itszoose 

This is known issue. You can update to [v4.0.0](https://github.com/panoply/vscode-liquid/tree/next) by downloading the VSIX file and installing it manually which irons out that logic. In **v4.0** the extension no longer uses Prettify but instead [Æsthetic](https://github.com/panoply/esthetic) has superseded that project. In Æsthetic this defect will not occur.:

If you need help upgrading manually, let me know. I plan to ship **4.0.0** very soon but there are a ton of breaking changes and updates, most of which pertain to Formatting and Completions etc.
