### ISSUE TITLE
[4.0] settings_schema.json validations tweaks

### ISSUE THREAD

**Issue by muchisx** [panoply/vscode-liquid#161]
Hi, I have a few proposed tweaks for the validations in this file.
I am using the latest vsix file in the `next` branch.

All of the tests can be found in my Tests Repo for Liquify for easy replicating
https://github.com/muchisx/Liquify-Shopify-test-bench

### **Current**
![image](https://github.com/panoply/vscode-liquid/assets/34131801/17841b99-4ac2-428e-a6b3-910e37b75304)

### Reasoning
If you can see, most themes not longer use this, so maybe enforning this with a warning can be not too good for DX, not even Dawn adds it !

https://github.com/Shopify/dawn/blob/95ac432f3477b005bf1e665b38a131bc1dac689d/config/settings_schema.json#L2-L9

## 2) Add the following `input-setting types` to the accepted values for `settings/type` for the first set of settings.

So, seems like the first set of settings in the `settings_schema` array don't benefit from the updated list of possible setting-types, so there might be an issue here.

### `header`
![image](https://github.com/panoply/vscode-liquid/assets/34131801/4b8e7d83-258c-49c1-b1ef-e7bdd95ed7b0)

### `color`
![image](https://github.com/panoply/vscode-liquid/assets/34131801/23e73a03-d422-444b-bf84-59e616363e73)

### `color_background`
![image](https://github.com/panoply/vscode-liquid/assets/34131801/51aa400e-b276-471b-9c68-ca0904c5b881)

### `paragraph`
![image](https://github.com/panoply/vscode-liquid/assets/34131801/3fbe3156-b12c-46cf-9773-2aa3ac3ad246)

... etc, there might be others but it should be the same idea.

### You can see here that the second settings item in the `settings_schema` array doesn't have any problem with the updated types.

![image](https://github.com/panoply/vscode-liquid/assets/34131801/a8e26283-fd54-417f-9938-827d857ee643)

## 3) Schema Autocomplete only works in the first item of the `settings_schema` array

These seem like useful snippets, but only work on the first item of the `settings_schema` with a `settings` property for some reason, also they are very limited, don't include all of the possible types.

https://github.com/panoply/vscode-liquid/assets/34131801/a5e07a48-5390-4667-b9c7-5918d2d7bac1

**Comment by panoply** [comment]
Thanks for this @muchisx 

I'll upstream to [Liquify Schema](https://github.com/panoply/liquify-schema) which is responsible for this Schema Stores. It seems I've done [some work](https://github.com/panoply/liquify-schema/blob/master/stores/shopify-settings_schema.json) on this but I'll need to go over it again. If you are familiar with JSON Schema Store specifications feel free to PR but I'll likely have this patched tonight.

**Comment by panoply** [comment]
@muchisx test this in the latest VSIX - We need to do some work on the new structure, but I have published the `.old` suffixed files within Liquify schema before your overhaul.
