### ISSUE TITLE
[4.0] Section & Snippets Autocomplete not working when using config.method = workspace

### ISSUE THREAD

**Issue by muchisx** [panoply/vscode-liquid#162]
Hi, basically the title.
I am using the latest vsix file in the `next` branch.

All of the tests can be found in my Tests Repo for Liquify for easy replicating
https://github.com/muchisx/Liquify-Shopify-test-bench

https://github.com/panoply/vscode-liquid/assets/34131801/71803f13-9042-4d84-9028-4e614d83834e

**Comment by panoply** [comment]
Following our chat in discord. Still haven't got around to this, will try tackle tonight. Folks have been waiting for 4.0 for far too long. Need to get some ground work applied here and supporting workspace settings is very much imperative, especially for cases like you were you are constantly switching between projects and the `.liquidrc` is a hassle. 

I'll notify when patched.

**Comment by muchisx** [comment]
Sounds good! 
I think it can benefit all of those that work for many projects in a day and prefer a global config for all of them.

**Comment by panoply** [comment]
Still not done on this. Will keep open for now.

**Comment by panoply** [comment]
Patched in https://github.com/panoply/vscode-liquid/commit/22584c96b22c740b4290d438a2646088656f6bb3
