### ISSUE TITLE
[4.0] `t` filter missing

### ISSUE THREAD

**Issue by davidwarrington** [panoply/vscode-liquid#163]
`t` is missing from the list of available filters.

![image](https://github.com/panoply/vscode-liquid/assets/9138568/76468626-5d4f-4455-8ba0-72137381b4bf)

As an aside thanks to your extension I discovered the `translate` filter which is an alias of `t` 🎉

**Comment by panoply** [comment]
Will cover in #165

**Comment by panoply** [comment]
🚢
