### ISSUE TITLE
[4.0] Incorrect completions when passed as variables to `t` filter

### ISSUE THREAD

**Issue by davidwarrington** [panoply/vscode-liquid#165]
I'm trying to pass the customer name to the `t` filter but the completions I'm receiving match the options available in my `*.default.json` rather than the actual object I'm trying to access (`customer`, in this instance).

![image](https://github.com/panoply/vscode-liquid/assets/9138568/e60e1168-d6fb-430d-b6bc-4b1c7f4ee365)

**Comment by panoply** [comment]
Fixed in the nightly babe xx
