### ISSUE TITLE
indenting in frontmatter is removed

### ISSUE THREAD

**Issue by elmuerte** [panoply/vscode-liquid#167]
```
---
foo:
  bar: quux
---
the actual liquid code
```

After formatting it is turned into

```
---
foo:
bar: quux
---
the actual liquid code
```

Workspace settings:

```json
{
    "liquid.engine": "11ty",
    "liquid.format.endNewLine": true
}
```

endNewLine also doesn't seem to be working.

Version: v3.2.2

**Comment by elmuerte** [comment]
Reinstalled the plugin, which appears to have partially fixed the formatting. Still no newline at of the file, but at least my frontmatter isn't mangled anymore.

**Comment by panoply** [comment]
@elmuerte Might be best to jump onto **v4.0** which is almost ready for the big time. Around 100 or so developers already leveraging it. It's really easy to upgrade, follow these steps:

https://github.com/panoply/liquify/discussions/23#discussioncomment-6610093

---

In terms of `endNewline` - the extension will respect your presets defined in VSCode and inherit them accordingly. I'd say this is related to `editor.renderFinalNewline` - In any sense, upgrade to 4.0 and this should be resolved.
