### ISSUE TITLE
[4.0] "in" in string breaking syntax highlighting

### ISSUE THREAD

**Issue by davidwarrington** [panoply/vscode-liquid#170]
https://github.com/panoply/vscode-liquid/assets/9138568/a77e443a-86ce-4d90-a95e-6deeabf08ae0

Fortunately I will be moving this to locales anyway but it had me really confused at first

**Comment by panoply** [comment]
This one _should_ be patch in next nightly bump.

**Comment by panoply** [comment]
🚢
