### ISSUE TITLE
[LiquidDoc] Lone single quote in comment breaks plugin

### ISSUE THREAD

**Issue by davidwarrington** [panoply/vscode-liquid#176]
```liquid
{% comment %}
  There's a non-breaking single quote in this line

  Accepts:
  - update_url: {Boolean} There's a breaking single quote here

  Usage:
  {% render 'product-variant-picker', product: product %}
{% endcomment %}
```

In the above example the first single quote after LiquidDoc begins appears to be detected as opening a string. The syntax highlighting breaks, and after the comment I no longer get autocompletions. A single quote in a word before `Accept:` seems to be ignored as expected. 

I found this in the `product-variant-picker` snippet in Dawn.

**Comment by panoply** [comment]
Should maybe make some action on in previous chats pertaining to Liquid docs. Will patch in meantime.
