### ISSUE TITLE
Support Liquid in HTML files with suffix '.html'

### ISSUE THREAD

**Issue by ZhiZe-ZG** [panoply/vscode-liquid#190]
Jekyll support using liquid in HTML. But the suffix of HTML file should be '.html'. This won't be recognized by the vscode-liquid.

**Comment by panoply** [comment]
Use file associations:

```jsonc
{
    "files.associations": {
        "*.html": "liquid"
    }
}
```

**Comment by ZhiZe-ZG** [comment]
@panoply  Thanks it works. However, please consider adding this functionality to the plugin (at least as an optional feature). Thanks again.

**Comment by panoply** [comment]
Hey, 

In previous versions this was a default, but it was problematic for developers. The preferred approach here is to use file associations. 

Happy it helped!
