### ISSUE TITLE
{% schema %} syntax highlight 

### ISSUE THREAD

**Issue by ronnypdev** [panoply/vscode-liquid#21]
<img width="1637" alt="Screen Shot 2019-07-16 at 11 05 56 AM" src="https://user-images.githubusercontent.com/24704656/61306167-19326700-a7ba-11e9-82c7-a3bd1e2c7a9c.png">

Hi @panoply 

so my {% schema %} syntax highlight it's broken. I honestly don't what happen, maybe it was after vs code update.

can you please advice?

**Comment by panoply** [comment]
Hey @ronnypdev I am unable to recreate this issue. I have tested on latest VS Code version. Can you send me the code  opposed to screenshot? also, let me know the following:

- What color theme are you using? 
- Have you checked the schema content JSON is correct?
- Are you using any other extensions the may conflict with Liquid? (as mentioned in documentation)

**Comment by ronnypdev** [comment]
Hi @panoply 

- I'm currently using the material Planenight theme
- I validated my JSON with the JSONLint and everything is properly formatted 
- I had the Liquid Language Support & Shopify Liquid Template Snippets extension install, but I already uninstall both and restarted my vs code and the schema syntax highlight is still broken

**Comment by panoply** [comment]
Hey @ronnypdev I have tested this theme and unable to recreate the issue. Send me your extensions list and settings configuration. There is most likely a conflicting issue somewhere.

**Comment by ronnypdev** [comment]
Hi @panoply

here are my extensions and user settings.

<img width="1680" alt="Screen Shot 2019-07-18 at 10 34 00 AM" src="https://user-images.githubusercontent.com/24704656/61466906-bae7be80-a948-11e9-8da6-87e136901c9c.png">
<img width="607" alt="Screen Shot 2019-07-18 at 10 37 56 AM" src="https://user-images.githubusercontent.com/24704656/61466907-bae7be80-a948-11e9-8645-90dac4bfc7d0.png">
<img width="606" alt="Screen Shot 2019-07-18 at 10 38 26 AM" src="https://user-images.githubusercontent.com/24704656/61466909-bae7be80-a948-11e9-94e6-3123c068348c.png">
<img width="623" alt="Screen Shot 2019-07-18 at 10 39 39 AM" src="https://user-images.githubusercontent.com/24704656/61466910-bae7be80-a948-11e9-9a09-60e3984b7994.png">
<img width="596" alt="Screen Shot 2019-07-18 at 10 39 59 AM" src="https://user-images.githubusercontent.com/24704656/61466911-bb805500-a948-11e9-866a-87c8a8379843.png">


please let me know if you need anything else from me?

**Comment by panoply** [comment]
Hey @ronnypdev, there are several extensions here that might be conflicting. I haven't got the time to test all of these but my suggestion moving forward is for you to disable extensions that manipulate grammars and syntax and try dissect which extension might be causing the issue. 

Are you defining any `tokenColorCustomizations` in your settings preferences?

**Comment by ronnypdev** [comment]
Hi @panoply 

I solve the problem. The conflicting extensions were TWIG Pack & Drupal Syntax Highlighting I uninstalled these extensions and it fixed the problem.

Thank you for your help.

**Comment by panoply** [comment]
@ronnypdev great! Glad you could resolve it. Try and use a workspace in the future to help prevent these type of things from happening.
