### ISSUE TITLE
Schema preset - "categorey" instead of "category"

### ISSUE THREAD

**Issue by RomainDW** [panoply/vscode-liquid#22]
Hi @panoply 

When typing "preset" and pressing tab, autocompletion writes "categorey" instead of "category" :

![categorey](https://user-images.githubusercontent.com/35602101/61378943-c682a900-a8a6-11e9-9771-033142bff0be.png)

**Comment by panoply** [comment]
Hey @RomainDW – Thanks for this, I totally missed it. Version 2.2.1 fixes this.
