### ISSUE TITLE
Would you like help?

### ISSUE THREAD

**Issue by colonelrascals** [panoply/vscode-liquid#23]
Hey man I use liquid everyday at work and would love to help with this. Are you interested in having a helping hand?

**Comment by panoply** [comment]
Hey @colonelrascals,  Are you familiar with tmLanguage grammars and the VS Code API? The extension seems to generating good growth with over 100+ new users everyday. I'm always open to extra support.

**Comment by colonelrascals** [comment]
familiar enough, I got decent exposure from my work on parinfer. I've forked the repo and will give it a look over to see if I can resolve any open issues!

**Comment by panoply** [comment]
Sounds good! I'll add you as a collaborator. No stress, help out where you can.
