### ISSUE TITLE
Error when doing the quickstart

### ISSUE THREAD

**Issue by TheOddler** [panoply/vscode-liquid#24]
When I follow the quickstart, and try to run `Liquid: Generate .liquidrc File` I get the following error:

    command 'liquid.liquidrc' not found

![image](https://user-images.githubusercontent.com/1831376/61386317-5e3ac400-a8b4-11e9-9da1-044aa9960627.png)

Any idea why this happens, or what I can do to find out?

**Comment by panoply** [comment]
Hey @TheOddler, what's your directory structure look like?

- Try restarting VS Code
- Make sure you're running the command from within 

See the below example from a Jekyll project:

![example](https://user-images.githubusercontent.com/7041324/61388388-20d83580-a8b8-11e9-8e2c-df80e0dbce0d.gif)

**Comment by colonelrascals** [comment]
Also make sure you've added the file root directory as a workspace.

**Comment by colonelrascals** [comment]
Would you like the functionality to work from a non-workspace? This could be accomplished by using window.activeTextEditor @panoply thoughts?

**Comment by panoply** [comment]
@colonelrascals worth integrating to prevent this from occurring for non-workspace users.

**Comment by TheOddler** [comment]
Yea, I don't think I'm using a workspace for this, just opened the folder in vscode. So that's probably the problem indeed. Would be nice if it worked in non-workspaces too.

**Comment by panoply** [comment]
@colonelrascals I'll implement this over the weekend unless you want to?

**Comment by colonelrascals** [comment]
@panoply I won't be able to make any meaningful progress until later this week.

**Comment by TheOddler** [comment]
What is the current progress on this?

**Comment by panoply** [comment]
@TheOddler It's coming. Next version will have it implemented.

**Comment by TheOddler** [comment]
Awesome, thank you so much for your work!

**Comment by laurens94** [comment]
I'm having the same issue, even when working from within a Workspace. I tried reinstalling the extension and restart VSC.. What can I do to debug?

**Comment by darkguy2008** [comment]
Same here, with or without workspace. Any ideas?

**Comment by nelsonvassalo** [comment]
Sorry this doesn't seem to be solved. Just ran through it yesterday after a fresh install from VS Marketplace…

**Comment by MenschLennart** [comment]
Yes happens for me too. Seems to be back for some reason. Could you go over it again?

**Comment by gamepad-coder** [comment]
Same problem, workspace is saved for root folder.

Steps:

1. Installed fresh VS Code.
2. Saved root folder as workspace in VS Code.
3. Installed a few other extensions.
4. Installed Liquid.
5. Command `Liquid: Generate .liquidrc File` ran properly.
6. Disabled Liquid while trying other extensions.
7. Enabled Liquid. (Can't remember whether commands worked at this point) 
8. Uninstalled Liquid. Restarted VS Code. Removed .liquidrc file.
9. Reinstalled Liquid.
10. Command `Liquid: Generate .liquidrc File` does not run at all.
    All Liquid commands result in an error with format:
    `Command 'Liquid: {{ liquid cmd name }}' resulted in an error`
    Liquid Extension icon/bar does not appear at the bottom of any tab.

Not sure if this is normal or not, but after uninstalling Liquid extension from VS Code, the folder@
C:\Users\(username)\.vscode\extensions\sissel.shopify-liquid-2.3.0\ was still present.

Windows 10.

Attempted removing this folder + contents, uninstalling Liquid extension, reinstalling, and problem persisted.

**Comment by Cabemo** [comment]
> Hey @TheOddler, what's your directory structure look like?
> 
> * Try restarting VS Code
> * Make sure you're running the command from within a root directory
> 
> See the below example from a Jekyll project:
> 
> ![example](https://user-images.githubusercontent.com/7041324/61388388-20d83580-a8b8-11e9-8e2c-df80e0dbce0d.gif)

Restarting worked for me

**Comment by panoply** [comment]
Hey guys, just to keep you all in the loop. 

There is an issue here that is affecting window users. Until I have time to conclude on the next major release, the workarounds are as @Cabemo referenced, by trying to restart and if that fails you can simply create a new `.liquidrc` file at root and copy the JSON found [here](https://github.com/panoply/vscode-liquid/blob/master/.liquidrc).

**Comment by elevatemystore** [comment]
I am getting the error below when trying to generate a .liquidrc file following the instructions from the quickstart. I have followed the advice in this thread and created a workspace for my project as well as restarting vscode and none of that resolved the issue.

I haven't seen any updates since 2019 for this project, is it not being updated anymore? I am just wondering whether it is worth sticking with this extension or if I should use one of the few other alternatives. 

`Command 'Liquid: Generate a .liquidrc rule file' resulted in an error (command 'liquid.liquidrc' not found)`

**Comment by panoply** [comment]
🚢  Shipped [v3.0.0](https://github.com/panoply/vscode-liquid/releases/tag/v3.0.0)

This error should no longer be a thing. Take a look at readme and release notes
