### ISSUE TITLE
Incorrectly colouring JavaScript Files

### ISSUE THREAD

**Issue by matthew1534** [panoply/vscode-liquid#25]
JavaScript files are coloured incorrectly - they contain no Liquid (this particular project doesn't contain liquid).

This is broken in v2.2.0 & v2.2.1

It seems if I have this it works but change the -- to --- and it breaks:
 console.log(`/-- Step 1: DO THIS --/`);

This is correct (using v2.1.5):
![Screenshot 2019-07-19 at 10 17 19](https://user-images.githubusercontent.com/30322136/61524631-b980c980-aa0e-11e9-89b9-d620ff3476f2.png)

This is wrong:
![Screenshot 2019-07-19 at 10 17 36](https://user-images.githubusercontent.com/30322136/61524643-bf76aa80-aa0e-11e9-9cdc-3071718522b4.png)

**Comment by panoply** [comment]
@matthew1534 thanks for this. I will have a fix in v2.2.2 released over weekend – Just out of curiosity, why are you using literals to define non-placeholder strings?

**Comment by matthew1534** [comment]
@panoply amazing, thanks :)

We default to using template literals (other than in `require("asd")` ) as in the majority of cases we are building strings from variables.
