### ISSUE TITLE
Regardless of what my tab/space size is set as in the settings, the formatter indents by 4 spaces

### ISSUE THREAD

**Issue by adrianocr** [panoply/vscode-liquid#26]
Regardless of what my tab/space size is set as in the settings, the formatter indents by 4 spaces

Latest vscode, latest version of the extension. 

Tabs set to spaces, tab size set to 2. But when I format the document or selection, every line gets indented by 4 spaces.

**Comment by panoply** [comment]
Seems unrelated to this extension and some context would be good.  Settings preferences will take precedence over Liquid format settings (logically). 

- Are you using a .liquidrc file?
- Do you have an .editorconfig  file in your root?
- What is your `editor.tabSize` config in your settings.json file?

**Comment by adrianocr** [comment]
@panoply sorry for wasting your time, I corrected the issue by resetting my vscode settings back to default. 

Must have been an unrelated settings or extension.

**Comment by panoply** [comment]
@adrianocr no problems! Glad you got it sorted. Always happy to help users, so never hesitate to reach out and no time wasted! Enjoy.
