### ISSUE TITLE
Syntax Highlight Still Breaking On Triple Dashes

### ISSUE THREAD

**Issue by james0r** [panoply/vscode-liquid#27]
I know we resolved this, I think in liquid comments before, but I'm still getting it in schema settings. 

![page-](https://user-images.githubusercontent.com/34731936/61902979-4678c680-aed8-11e9-896b-af8ba202fd47.png)

**Comment by panoply** [comment]
Related to #25 – Fix is coming this week.

**Comment by panoply** [comment]
v2.2.2 fixes this. Let me know if you run into anymore issues.
