### ISSUE TITLE
No Licence

### ISSUE THREAD

**Issue by matthew1534** [panoply/vscode-liquid#30]
At the moment there is no licence on this repo/VS Code extension - I guess it is intended that it is MIT? If that is the intention could this be added?

Thanks Matthew

**Comment by panoply** [comment]
Hey @matthew1534 there are currently no plans in licencing this extension under MIT as reselling is permitted under MIT. In due time the extension will move into the direction of paid licencing. 

Keep in mind that the intricacies of the paid licencing and the advanced features that will be available with it are still some time away. 

Hope this helps.
