### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by entozoon** [panoply/vscode-liquid#35]
The `Add line comment` command, or similar, creates `<!-- foo -->` within .liquid files.
It might be preferable for it to create `{% comment %} foo {% endcomment %}` instead, if possible?

The benefit being that the liquid compiler will strip these out, so it is the best way to add comments to liquid files, typically

**Comment by panoply** [comment]
So currently,  [PrettyDiff](https://github.com/prettydiff/prettydiff) handles this rule but internally it's parser ([sparser](https://github.com/unibeautify/sparser)) has some trouble with Liquid comments. Providing support for this would require taking control of comment formatting away from Sparser and creating an internal solution which I agree would be worth applying.

I will looking into this post v2.4.0.

**Comment by panoply** [comment]
🚢  Shipped [v3.0.0](https://github.com/panoply/vscode-liquid/releases/tag/v3.0.0)
