### ISSUE TITLE
Can't Disable Snippets

### ISSUE THREAD

**Issue by james0r** [panoply/vscode-liquid#40]
I was fine with these before, but now i'm noticing that they're taking precedent over Emmet snippets which is fairly annoying.

is there a flag to be able to disable snippets suggestions just from the extension?

**Comment by panoply** [comment]
Hey @james0r, so the next version (2.4) will mostly likely drop snippet support and instead provide them as a separate extension or if the maintainer of [vscode-liquid-snippets](https://github.com/killalau/vscode-liquid-snippets) eliminates its extension dependency you will be able to use that project. Unfortunately [my request](https://github.com/killalau/vscode-liquid-snippets/issues/13) for this has fallen on deaf ears, so a separate extension is most likely the future option to take.

The new version will provide code completions and intellisense for the Standard, Shopify and Jekyll Liquid engines, which in-turn will become the replacement for Snippets as you will get completions (snippets) as you write syntax.

**Comment by panoply** [comment]
🚢  Shipped [v3.0.0](https://github.com/panoply/vscode-liquid/releases/tag/v3.0.0)

Snippets no longer associate to HTML and instead completions are something you can leverage.
