### ISSUE TITLE
PrettyDiff: 2 more start types than end types.

### ISSUE THREAD

**Issue by Falco-Technology** [panoply/vscode-liquid#42]
When attempting to format a large file (.liquid) I get an error in the output panel "PrettyDiff: 2 more start types than end types." and the document is not formatted.

I assume this means the document cannot be formatted due to a syntax error but there is no hint as to which line. I tested the extension on a small document and it worked without issue.

What does this error code mean? How can I determine the source of the syntax error?

**Comment by panoply** [comment]
This means that you have incorrect syntax. Generally, it indicates that you're missing an `{% endtag %}` somewhere in your code. For example, take the following:

```liquid
{% if tag == something %} 
  {% for tag in tags %}
{% endif %}  
```
This would be invalid code as the `{% for %}` tag is missing an ender. PrettyDiff will be unable to format and will throw that error. Unfortunately PrettyDiff doesn't give us line numbers or position locations of errors so in this current version (2.3) diagnostic features ("hints") are not available. You will need to go over your code and find out where you are missing that end tag be it a endfor, endif, endcase etc. 

#### Version 2.4^
In the next release (2.4) I have tackled this issue and your Liquid code will be validated before passing it to the formatter (prettydiff) so you will be able to see where these errors are occuring. Until then, you will need to diagnose these problems manually.

**Comment by aaronmw** [comment]
`[1/25/2021, 9:51:32 PM] PrettyDiff: 1 more end type than start types.`

I can't spot anything wrong with my file 🤔
