### ISSUE TITLE
Liquid syntax is throwing an error

### ISSUE THREAD

**Issue by deepfriedbrain** [panoply/vscode-liquid#44]
I'm using this extension for the first time. I have a .js.liquid file but after installing this extension I get the following error on liquid syntax:

![image](https://user-images.githubusercontent.com/21341237/73611534-b7ceca00-461d-11ea-82f3-717b78d1d1df.png)

Can someone help me figure out what could be wrong? I have not made any changes to the generated .liquidrc file yet.

**Comment by panoply** [comment]
Unrelated to to this extension. (ts1109) means typescript not Liquid.

**Comment by deepfriedbrain** [comment]
Thanks for your reply, but I'm getting this only after adding this Liquid extension. If I don't include this extension, then I lose syntax highlighting but I don't get any error. 

Is there any workaround to this? There's absolutely nothing wrong with my file.

**Comment by panoply** [comment]
You can simply disable JavaScript validation within vscode workspace settings. Press `cmd+shift+p` goto Preferences > Open Settings (JSON) and add the following line:

```json
{
  "javascript.validate.enable":  false
}
```

Read the [docs](https://code.visualstudio.com/docs/getstarted/settings) man.

**Comment by deepfriedbrain** [comment]
Well, that's neither a solution nor a workaround. I don't want to disable Javascript validation across the board.

The point is that after adding this plugin, I thought it would allow liquid syntax to work well within javascript files while providing syntax highlighting.

The number of .js.liquid files is just a minuscule portion of the total js files in my various projects. I would just remove this plugin and live without syntax highlighting on a few .js.liquid files.

And yeah, I'll read the docs and hope to be as smart as you someday! 

Thank you.

**Comment by panoply** [comment]
Ush! I just re-read what I wrote. I was in a rush and not really paying attention when I replied. Sorry bud! I did not mean to at all come across that way! (My apologies!).

To give you some insight as to why you're getting these errors. TypeScript doesn't  understand Liquid, so you get those errors. If you're using ESLint, you can do:

```json
  "eslint.validate": [
    "javascript",
    "javascriptreact",
    /*
        Use below settings when working with `<script>` tags.
        Apply validating based on language as workspace settings.
      */
    {
      "language": "html",
      "autoFix": false
    },
    {
      "language": "liquid",
      "autoFix": false
    }
  ]
```

You can also try with just Liquid:

```json
 "[liquid]": {
    "javascript.validate.enable":  false
  }
```

**Comment by duterte** [comment]
I encounter the same Issue. Why they did not fix this ?
