### ISSUE TITLE
Respect editor settings or allow using tabs

### ISSUE THREAD

**Issue by passcod** [panoply/vscode-liquid#49]
My project is set to use tabs everywhere (except for yaml), but the auto-formatter in this extension does not respect that, and I cannot see a way to customise indenting behaviour for HTML in the liquidrc.

Could this extension either respect the indent preferences or allow the indenting options to be set for all liquid file types?

**Comment by panoply** [comment]
Hey I'll ship this in Liquify (next major) and notify you when released.

**Comment by passcod** [comment]
Thanks :heart:

**Comment by sebszocinski** [comment]
Any updates on this?

**Comment by robbaenrobba** [comment]
We need this setting! Now i have to convert from spaces to tabs when formatting + i have to save without format afterwards because it will bring back the spaces when i save (to format).

settings.json
```json
  "editor.tabSize": 4,
  "editor.insertSpaces": false,
  "editor.formatOnSave": true,
  "liquid.format": true,
  "files.associations": {
    "*.liquid": "html"
  },
  "[html]": {
    "editor.defaultFormatter": "sissel.shopify-liquid"
  },
```

**Comment by panoply** [comment]
In the current version you can use “indent_size” size setting which defaults to 2. If you want tabs you can use “indent_char” and set “\t” in tabs in the liquidrc file.

**Comment by robbaenrobba** [comment]
Thank you for the quick response! 💌  

I tried your solution, but the indenting gets bananas :/ but it works-ish! Think i'll keep to the method until it get fixed in future releases!

Example:
```
<div class="container">
				<div class="row">
								<div class="col-md-4">
												<img src="/img/logo.png">
								</div>
								<div class="col-md-4 centre">
												<a class="btn btn-default" data-toggle="modal" href="#terms">Terms &amp; Conditions</a>
								</div>
								<div class="col-md-4 right">Large File Transfer System</div>
				</div>
</div>

<div class="modal fade" id="terms">
				<div class="modal-dialog">
								<div class="modal-content">
												<div class="modal-header">
																<button class="close" data-dismiss="modal" type="button">×</button>
																<h4 class="modal-title">Terms &amp; Conditions</4>
												</div>
												<div class="modal-body">
																<p>My terms and conditions.....</p>
												</div>
												<div class="modal-footer">
																<a class="btn btn-primary" data-dismiss="modal" href="#">Close</a>
												</div>
								</div>
				</div>
</div>

```

**Comment by panoply** [comment]
It is possible to do, I just forget the settings to make it work. It must be frustrating for you. From the example it seems to indenting 4x tabs. I will try get back to you regarding this.

**Comment by robbaenrobba** [comment]
Tack you @panoply i appreciate it alot!

**Comment by panoply** [comment]
This was resolved in Prettify.
