### ISSUE TITLE
Formatting splits td tags

### ISSUE THREAD

**Issue by MiBuena** [panoply/vscode-liquid#50]
When I try to format a table, it splits some of the td tags to 2 lines like this. 

            <td>{{Product.TotalSum}}
                €</td>

Is there a way to prevent td tags from breaking?

**Comment by panoply** [comment]
Use `{{ product.totalsum | prepend: “€ ”}}` this can also be fixed with formatting option applied to HTML but I’m unsure which option controls that aspect.

**Comment by MiBuena** [comment]
Thank you for your answer!

However, since we are talking about a very long document - it will require a lot of effort to change it everywhere.

If anyone knows which option controls this - it will help me very much!

**Comment by panoply** [comment]
Select the tag, ‘cmd+shift+d‘ in vscode will allow you to select all tags that match that selection, might be of some help.

**Comment by panoply** [comment]
This can be configured using [Prettify](https://github.com/panoply/prettify) rules. Take a look at [v3.0.0 Release Notes](https://github.com/panoply/vscode-liquid/releases/tag/v3.0.0) and the new [Readme](https://github.com/panoply/vscode-liquid)
