### ISSUE TITLE
Extension should only affect liquid tags

### ISSUE THREAD

**Issue by aes421** [panoply/vscode-liquid#52]
I had to uninstall this plugin because it was causing syntax errors in my other projects which are written with Angular.

When I saved a .html file in Angular this extension was auto "correcting" syntax from `routerLink` to `routerlink`.  This broke all links in my Angular project.  This is just one example.

This extension should only be affecting liquid syntax, not all HTML syntax.

**Comment by panoply** [comment]
Hey @aes421 – This version leverages Grammar injections which causes this issue.  This has been addressed in the next release.

**Comment by duterte** [comment]
> I had to uninstall this plugin because it was causing syntax errors in my other projects which are written with Angular.
> 
> When I saved a .html file in Angular this extension was auto "correcting" syntax from `routerLink` to `routerlink`. This broke all links in my Angular project. This is just one example.
> 
> This extension should only be affecting liquid syntax, not all HTML syntax.

This extension also cause me lots of troubles, would you tell me your other way ?

**Comment by panoply** [comment]
🚢  Shipped [v3.0.0](https://github.com/panoply/vscode-liquid/releases/tag/v3.0.0)

Grammar injections are no longer applied in HTML. The language is now recognized as Liquid.
