### ISSUE TITLE
Hope to make liquid code foldable

### ISSUE THREAD

**Issue by xyyolab** [panoply/vscode-liquid#53]
![Screen Shot 2020-07-29 at 12 43 29](https://user-images.githubusercontent.com/48758247/88754228-1c1bb200-d199-11ea-9297-d2a529e6cc06.png)

# Feature request
## Get folding with liquid code(`⌄`)
We can fold HTML code, but not liquid code, hope someone can help us.
Thanks!!!

**Comment by panoply** [comment]
Use `"editor.foldingStrategy": "indentation"` in workspace settings of vscode.

**Comment by xyyolab** [comment]
Oh, it works!
Thanks!!!
