### ISSUE TITLE
I can't find v2.4

### ISSUE THREAD

**Issue by kamhung** [panoply/vscode-liquid#54]
I can't find v2.4, I need it.

**Comment by panoply** [comment]
Hey @kamhung v2.4 will actually be shipped as a major release (v3.0) and will adopt a new name, being 'Liquify' - I will notify you once it goes live.

**Comment by kamhung** [comment]
Thx

**Comment by iBug** [comment]
Hi @panoply are you still there?

**Comment by iBug** [comment]
ping?

**Comment by iBug** [comment]
Leaving this reference for future readers: <https://github.com/panoply/vscode-liquid/issues/56#issuecomment-833070334>

This issue might be better closed so discussion can be directed to #56.

**Comment by panoply** [comment]
Thanks! @iBug
