### ISSUE TITLE
front matter in scss

### ISSUE THREAD

**Issue by irik77587** [panoply/vscode-liquid#57]
every front matter file starts with 
```
---
// Some key value pairs if needed
---
```
but in scss files, vscode shows error. In standard scss file it is indeed error. But in liquid, it shouldn't be. Hence I can't save the file with format document enabled. I can still save the file manually outside vscode but then what's the point of using an IDE.

**Comment by cdeath** [comment]
more of a jekyll issue but yes... no front matter support breaks everything

**Comment by panoply** [comment]
This issue was addressed in **3.x.x** and frontmatter will gracefully  be handled.
