### ISSUE TITLE
Issue with status icon

### ISSUE THREAD

**Issue by jack-fdrv** [panoply/vscode-liquid#59]
There is something wrong. When I try click on Enable formating, it shows like it enable but the status do not change.
![ezgif-3-1fbb91d547e6](https://user-images.githubusercontent.com/4230282/99018588-1f2d8900-2563-11eb-9405-5eae6b597322.gif)

**Comment by bbudescu** [comment]
I get the same behavior. What kind of extra information is required?

**Comment by panoply** [comment]
Hey guys, this should be fixed in [v3.0.0](https://github.com/panoply/vscode-liquid/releases/tag/v3.0.0). Take a look at the new [readme](https://github.com/panoply/vscode-liquid) and open a new issue if you are still having trouble.
