### ISSUE TITLE
Snippet for checkbox setting has invalid default value

### ISSUE THREAD

**Issue by larsschellhas** [panoply/vscode-liquid#60]
The snippet for a checkbox setting results in this code: 
```liquid
{
    "type": "checkbox",
    "id": "id",
    "label": "label",
    "default": "true",
    "info": ""
},
```

However, the default value needs to be boolean and not string - the hypens need to be removed.
Furthermore, I think it would be better to remove the comma from the snippets. Much more often, I happen to have a comma too much now in my schemas instead of one to few.

**Comment by panoply** [comment]
Hey @larsschellhas 

I am deprecating all the snippets for Shopify schema sections in the next version (Liquify). IntelliSense capabilities will facilitate completion features for this aspect. For example:


https://user-images.githubusercontent.com/7041324/103383860-9f4c8580-4af4-11eb-8877-102831af14a1.mp4

**Comment by larsschellhas** [comment]
Definitely seems like a nice way of doing it! I wonder if it saves more time than having the snippets, too (at least stripped down to the required parameters). :)

Have a good start into the next year and thanks for the great work! 😊

**Comment by panoply** [comment]
Will address this #121
