### ISSUE TITLE
Highlighting does not work

### ISSUE THREAD

**Issue by jarkin13** [panoply/vscode-liquid#62]
My liquid files look like this... 
<img width="521" alt="Screen Shot 2020-11-24 at 5 03 55 PM" src="https://user-images.githubusercontent.com/4195698/100165290-22841700-2e77-11eb-81d4-768d07628a50.png">

In addition, it keeps formatting to 4 spaces vs. 2 spaces — how can I correct this?

**Comment by panoply** [comment]
Hej, 

- Select HTML as the language in VSCode, not Liquid (this will change in next release, be aware).
- You can adjust spacing in your vscode preferences, or if you want you can leverage the `indent_size` ruleset, which you set to `2` in any sense, I'm pretty sure this version respects `.editorconfig` files. 

Hope it helps.

**Comment by panoply** [comment]
🚢  Shipped [v3.0.0](https://github.com/panoply/vscode-liquid/releases/tag/v3.0.0)
