### ISSUE TITLE
indent_size for HTML

### ISSUE THREAD

**Issue by bbudescu** [panoply/vscode-liquid#69]
Would be nice to be able specify the indent size for html tags when parsing and formatting liquid files. As far as I can see, it defaults to `4` and can't be changed, and also ignores `editor.tabSize` setting (which, in my case, is set to `2`, and is respected when I trigger the built-in formatting of vsCode (`Ctrl+Shift+i` on `Linux`)).

**Comment by panoply** [comment]
Use the ruleset of `indent_size`in the `.liquidrc`file, for example: 

```json
{
  "html": {
    "indent_size": 4,
    "correct": true,
    "force_attribute": false,
    "braces": false,
    "preserve": 1,
    "wrap": 80,
    "preserve_text": true,
    "content": true,
    "space_close": true,
   }
}

```

**Comment by bbudescu** [comment]
@panoply, thanks for the solution. How is it that `indent_size` property not documented under the `html` section? Is it a new feature, does it have some problems, or did I actually just miss it in the docs?

**Comment by panoply** [comment]
@bbudescu I most likely forgot to document it. I didn't work on the project for a long time and I really didn't expect so many people to use it, so it was a real hack job so-to-speak. When I started working on the next release (Liquify) last year, I neglected this version and maintenance on it, so this is on me and apologize as it must of been frustrating for you. 

Hope it resolved the issue.

**Comment by bbudescu** [comment]
@panoply, don't worry about it. Thanks for your work on this project. I totally understand how things tend to slip through the cracks, especially where there can't be a lot of time dedicated for topics ancillary to the coding (e.g., documentation, testing, management etc.).
