### ISSUE TITLE
help: closing braces of a liquid object

### ISSUE THREAD

**Issue by endepointe** [panoply/vscode-liquid#71]
after saving a .liquid file, the closing braces of a liquid object receive a space, like so:

`{{some_object}}`

to this:

`{{some_object} }`

This completely breaks the highlighting and produces a syntax error during live editing. I am not sure if this is a problem with vscode or the extension. I am not using any other extensions and have disabled the vscode settings for inserting spaces before and after braces.

any help is appreciated so I can move on. thank you

**Comment by panoply** [comment]
This issue persists in latest release but will be handled upstream in Prettify (next patch release, ie: v3.0.1). For the time being, you can leverage inline ignores, eg: 

```liquid
<!-- @prettify-ignore-start -->
{{some_object}}
<!-- @prettify-ignore-end-->
```

You can track it here: https://github.com/panoply/prettify/issues/28
