### ISSUE TITLE
Format key binding conflicts with default key binding on Mac.

### ISSUE THREAD

**Issue by ktnyt** [panoply/vscode-liquid#75]
On a Mac, VSCode maps `Cmd+Shift+L` to `Select All Occurrences of Find Match` by default. This plugin overwrites `Cmd+Shift+L` to `Liquid: Format Document` which is very degenerative to the UX. Any plugin **should not** overwrite any of the default key bindings in VSCode. Please consider remapping to another key combination or add `editorLangId == 'liquid'` to the key binding condition.

**Comment by panoply** [comment]
🚢  Shipped [v3.0.0](https://github.com/panoply/vscode-liquid/releases/tag/v3.0.0)

Apologies on this one. No more key bindings.
