### ISSUE TITLE
Liquid tag indenting messed up

### ISSUE THREAD

**Issue by SteveALee** [panoply/vscode-liquid#80]
I might be missing something but

```
{%- for item in include.data -%}
    {% assign newItem = item[1] -%}
{%- endfor -%}
```

ends up as 

```
{%- for item in include.data -%}
{% assign newItem = item[1] -%}
{%- endfor -%}
```

Same for if.

I tried the code in the PrettyDiffs web app and indenting is correct.

thanks

**Comment by panoply** [comment]
Hey @SteveALee 

Might caused from another syntax error within your code or you have not activated the extension correctly. See #32 and see how you go.

**Comment by SteveALee** [comment]
OK, thanks. No errors I can see and liquid in status bar has tick. Do have prettier so will figure out how to turn liquid off for the hrntl as you say that will be required in future. Will let you know.

**Comment by SteveALee** [comment]
@panoply Well after a lot of head scratching and deleting code I have a minimal example that fails. The strange thing is that liquid shows a tick until I started to cut out code

```liquid
{%- if include.type == 'start' -%}
    <script>
       foo(() => {})
    </script>
{%- endif -%}
```

the error is 

```
PrettyDiff: 1 more start type than end types.
```

**Comment by SteveALee** [comment]
it seems to be the fat arrow syntax rather than braces as this is fine

```javascript
      function f() {}
      foo(f)
```

**Comment by panoply** [comment]
Ahh, I see! so the current version does not play nicely with `<script>` tags, if memory calls me correct, they are ignored by default (internally) I believe. JavaScript and Liquid don't play at all and there has yet to be a fluid solution created for this. I do have some comforting news though. I tackled this issue and was able to bring support for JavaScript infused Liquid and in addition achieve formatting fluidity with the formatter that Liquify (Liquify is the next release of this extension) will run atop of.  

As such, I have addressed these cases within [Prettify](https://github.com/panoply/prettify). Prettify is a hard-forked variation of PrettyDiff itself. I stripped and refactored most of the existing code base and I was able to leverage its existing lexical analysis and parsing technique which resulted in Liquid + JavaScript formatting support. 

You can take a look at WIP of [Prettify](https://github.com/panoply/prettify). Unfortunately, I am still working through some features and aspects but wanted to drop it here as a reference point and assure you or any read the stumbles upon this issue that these capabilities and really annoying issues will be a thing of the past in Liquify.

**Comment by SteveALee** [comment]
> JavaScript and Liquid have historically not got along very well 

hmm, as a templating language I would expect it not to care whatever the content is at all. As lon a syou avoid it's synatx like `{%`. Also of course JavaScript in script tags is perfectly valid HTML (if not quite XHTML) :) We have cases of it in CSS files too. And Markdown, and...... Oh well

Prettify sounds interesting. I don't understand the VSCode language stuff but I guess the real problem with templates is you get a mixture of all types of content, along with varying files extensions too.

For now my workaround is to form selections and remember to save without formatting! Messy and fragile but it's OK.

Thanks for a very useful add-on.
