### ISSUE TITLE
Syntax Highlighting for vanilla HTML, JS, and CSS doesn't work.

### ISSUE THREAD

**Issue by zqlimy17** [panoply/vscode-liquid#82]
![Screenshot 2022-02-06 at 7 15 37 PM](https://user-images.githubusercontent.com/28788734/152678207-c84dbda8-da38-4e96-a6ad-df4e924ed998.png)
Syntax highlighting does not work with HTML, <style>, and <script> tags in .liquid files.

But {% style %} and {% javascript %} tags works normally. 

Right now, I'm using the HTML file association, everything is highlighting well, but I can't use liquid tags like {% shop.name %} in my <script> which prevents formatting.

**Comment by panoply** [comment]
Change the language to HTML.
