### ISSUE TITLE
Formatter adding extraneous whitespace on each line

### ISSUE THREAD

**Issue by flipchart** [panoply/vscode-liquid#9]
The formatter adds 44 spaces to the beginning of html lines. Frontmatter lines are spared. Removing the spaces and reformatting puts them back

I have format document on save, and have set the default formatter for html to sissel.shopify-liquid, but this also occurs when using Ctrl + Shift + L

**Comment by panoply** [comment]
Code examples would help

**Comment by flipchart** [comment]
```
// editor.json file
"[html]": {
	"editor.defaultFormatter": "sissel.shopify-liquid"
},
```

Before formatting:
```
---
title: "About My Awesome Site"
description: "A great description"
---

<p>
  Lorem ipsum dolor sit amet.
</p>
```

After formatting:
```
---
title: "About My Awesome Site"
description: "A great description"
---

                <p>
                    Lorem ipsum dolor sit amet.
                </p>
```

panopoly/vscode-liquid: v1.6.3

vscode:
Version: 1.33.1 (system setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

**Comment by flipchart** [comment]
It seems if there's a `<script>` tag, then formatting successive times increases the indent, and also places the cursor at the end of the file. It also appears that if I remove the extra whitespace, and reformat, it jumps back to the place where it was when the whitespace was there - like an indent variable not being reset between successive format invocations

Before format:
```
---
title: "About My Awesome Site"
description: "A great description"
---

<p>
    Lorem ipsum dolor sit amet.
</p>

<script type="text/javascript">
    alert("hi");
</script>
```

After format:
```
---
title: "About My Awesome Site"
description: "A great description"
---

                                                                                                                                        <p>
                                                                                                                                            Lorem ipsum dolor sit amet.
                                                                                                                                        </p>

                                                                                                                                        <script type="text/javascript">
                                                                                                                                            alert("hi");
                                                                                                                                        </script>
```

**Comment by panoply** [comment]
I will look into what is causing this but am extremely busy at the moment, As per the readme documentation, the formatter uses PrettyDiff under the hood, the extension only implements this as a formatter, so this issue might be PrettyDiff related, which I will investigate. 

FYI:

You do not need to define a default formatter, the extension does this by default, use the status bar icon to toggle formatting on/off when working in non liquid infused `.html` documents, so remove this:

```json
"[html]": {
    "editor.defaultFormatter": "sissel.shopify-liquid"
},
```

Script tags are ignored by default, don't rely on this formatter to handle `<script>` tag contents,  use Prettier/ESLint to handle formatting of these elements, if you don't how to implement that, then learn.

**Comment by panoply** [comment]
This should be fixed @flipchart
