### ISSUE TITLE
Starting configuration

### ISSUE THREAD

**Issue by outerpreneur** [panoply/vscode-liquid#90]
Hi, I ve doing shopify theme development for more than 6 months and I ve been struggling finding the right setting  formatting settings with VS code.

I currently have a local .liquidrc file and a workspace general settings, more or less the ones I have read in your comments helping others. 

.LIQUIDRC SETTINGS

 `{
  "ignore": [
    {
      "type": "liquid",
      "begin": "comment",
      "end": "endcomment"
    },
    {
      "type": "liquid",
      "begin": "capture",
      "end": "endcapture"
    }
  ],
  "html": {
    "correct": true,
    "force_attribute": false,
    "braces": false,
    "preserve": 1,
    "wrap": 85,
    "preserve_text": true,
    "content": true,
    "space_close": true,
    "tags": [
      {
        "tag": "source",
        "rules": {
          "force_attribute": true,
          "space_close": true
        }
      }
    ]
  },
  "js": {
    "preserve": 1,
    "method_chain": 0,
    "quote_convert": "none",
    "format_array": "indent",
    "format_object": "indent",
    "braces": false,
    "no_semicolon": false,
    "brace_block": true
  },
  "scss": {
    "css_insert_lines": true,
    "preserve": 2,
    "braces": false,
    "brace_block": true
  },
  "css": {
    "css_insert_lines": true,
    "preserve": 2,
    "braces": false,
    "brace_block": true
  },
  "json": {
    "preserve": 0,
    "braces": true,
    "brace_block": false,
    "no_semicolon": true
  }
}`

WORKSPACE SETTINGS

```
    "editor.defaultFormatter": "sissel.shopify-liquid",
    "editor.formatOnSave": true,
    "gitlens.codeLens.dateFormat": "",
    "files.associations": {
        "*.liquid": "html"
    },
    "gitlens.currentLine.dateFormat": "",
    "json.schemas": [
    
    ]
}
```

If you could answer the following questions, that would be much appreciated:

1. Can we have beautify and Liquid extension installed at same time? if yes, which one should be the main formatter?
2. When Liquid is the main formatter, my CSS files cant be auto-indented.. what should be  a way to fix this? it says Liquid extension can format CSS.
3. My formatter only works when the filed is displayed as HTML.. when is liquid, there is no sintax highlighting and format isnt working. What is the correct way? should we have them as liquid or HTML?
4. From what I understand, you are working on a new version called Liquify (along with prettify) which is not available yet from my understanding correct? what should we expect from this extension?

All this questions answered would help me very much in tunning the extension settings. Thank you very much!

**Comment by panoply** [comment]
🚢 Shipped - See [v3.0.0 Release notes](https://github.com/panoply/vscode-liquid/releases/tag/v3.0.0)
