### ISSUE TITLE
Publish extension on Open VSX

### ISSUE THREAD

**Issue by bertptrs** [panoply/vscode-liquid#91]
Due to various reasons outlined in https://github.com/Microsoft/vscode/issues/31168, open source builds and forks of VS Code cannot install extensions from the Visual Studio Marketplace. [Open VSX], an alternative extension registry, can be used from those platforms. Many extensions are published there in addition to the official marketplace, so open source builds can still use those extensions.

Would you consider uploading this Liquid extension there as well? Me and other users of vscodium/open source builds of vscode would be grateful.

[Open VSX]: https://open-vsx.org/

**Comment by bertptrs** [comment]
Thank you, looking forward to the result :)

**Comment by panoply** [comment]
Hey @bertptrs I will get around to this next month.

**Comment by bertptrs** [comment]
Hi Panoply, sorry to ask but is there anything I could help with in getting this out there?

**Comment by panoply** [comment]
Hey @bertptrs! Please don't apologise, all communication is welcome. 

So I have actually tried several times to make this a reality, but keep coming up with internal Server errors. I am not really well versed in Open VSX but from what I have understood, I am doing everything right, but I cannot seem to publish it. You are free to fork and build the VSIX, publish it on my behalf, but I might need to make you a maintainer.

**Comment by bertptrs** [comment]
Thanks for trying! It seems there have been some issues with OpenVSX recently. The https://github.com/rust-lang/rust-analyzer/ project had the same, but apparently they managed to work it out last Wednesday and now it's working for them.

Could you perhaps try to upload it again? Otherwise I'll fork and try my best on it myself. I have very little experience with Typescript but I know a thing or two about packaging, so that might cancel out.

**Comment by panoply** [comment]
@bertptrs we should be good now. I'll keep this open until namespace verification concludes. Hope it helps.

**Comment by bertptrs** [comment]
Much appreciated!
