### ISSUE TITLE
Multi-line element scripts indented too many times

### ISSUE THREAD

**Issue by Christopher-Hayes** [panoply/vscode-liquid#95]
![image](https://user-images.githubusercontent.com/6013871/175099135-6a442673-079a-4ba7-935a-583905634f9d.png)

### Description

Every time I run "Liquid: Format Document", the scripts after the `@click` line get indented like 20 times. If I run format again, it gets indented another 20 times.

This seems to only happen if I have the `{% if %}` inside the element properties. If I remove conditional, it indents as expected.

### Temporary work-around

Don't use `{% if %}` inside element properties.

**Comment by panoply** [comment]
Hey @Christopher-Hayes 

Thanks for the information. This was fixed in [Prettify](https://github.com/panoply/prettify) which will be used in future releases of the extension. If you can hold out a little longer I will ship a pre-release candidate for this.

**Comment by Christopher-Hayes** [comment]
Cool, thanks @panoply

**Comment by panoply** [comment]
🚢  Shipped [v3.0.0](https://github.com/panoply/vscode-liquid/releases/tag/v3.0.0)
